/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsList } from "../../funcs/alertsList.js";
import { ListAlertsRequest$zodSchema } from "../../models/listalertsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAlertsRequest$zodSchema.optional(),
};

export const tool$alertsList: ToolDefinition<typeof args> = {
  name: "list-alerts",
  description: `List alerts

Retrieve all alerts, including Signals alerts and third-party`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await alertsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
