/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audiencesGetSummary } from "../../funcs/audiencesGetSummary.js";
import { GetAudienceSummaryRequest$zodSchema } from "../../models/getaudiencesummaryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAudienceSummaryRequest$zodSchema,
};

export const tool$audiencesGetSummary: ToolDefinition<typeof args> = {
  name: "get-audience-incident-ai-summary",
  description:
    `Retrieves the AI-generated summary for an incident tailored to a specific audience. This is useful for:

  - Getting audience-specific incident summaries,
  - Viewing summaries customized for different stakeholders,
  - Understanding how incidents are communicated to different audiences.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audiencesGetSummary(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
