/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audiencesListSummaries } from "../../funcs/audiencesListSummaries.js";
import { ListAudienceSummariesRequest$zodSchema } from "../../models/listaudiencesummariesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAudienceSummariesRequest$zodSchema,
};

export const tool$audiencesListSummaries: ToolDefinition<typeof args> = {
  name: "get-incident-ai-summary",
  description:
    `Retrieves the AI-generated summary for an incident. This is useful for:

  - Getting a concise AI summary of an incident,
  - Understanding incident context quickly,
  - Reviewing automated incident summaries.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audiencesListSummaries(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
