/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audiencesGetAudience } from "../../funcs/audiencesGetAudience.js";
import { GetAudienceRequest$zodSchema } from "../../models/getaudienceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAudienceRequest$zodSchema,
};

export const tool$audiencesGetAudience: ToolDefinition<typeof args> = {
  name: "get-audience",
  description:
    `Retrieves detailed information about a specific audience by its ID. This is useful for:

  - Getting audience details and configuration when you have the audience ID,
  - Viewing audience information.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audiencesGetAudience(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
