/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audiencesListAudiences } from "../../funcs/audiencesListAudiences.js";
import { ListAudiencesRequest$zodSchema } from "../../models/listaudiencesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAudiencesRequest$zodSchema.optional(),
};

export const tool$audiencesListAudiences: ToolDefinition<typeof args> = {
  name: "list-audiences",
  description: `Lists all audiences in the organization. This is useful for:

  - Getting a list of all audiences with their IDs and names,
  - Finding an audience ID by searching through audience names,
  - Viewing audience configurations and details.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audiencesListAudiences(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
