/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catalogEntriesGetService } from "../../funcs/catalogEntriesGetService.js";
import { GetServiceRequest$zodSchema } from "../../models/getserviceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetServiceRequest$zodSchema,
};

export const tool$catalogEntriesGetService: ToolDefinition<typeof args> = {
  name: "get-service",
  description:
    `Retrieves detailed information about a specific service. This is useful for:

  - Getting service details including the team that owns it,
  - Finding which team is responsible for a service,
  - Viewing service configuration and metadata,
  - Identifying service ownership for incident response.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await catalogEntriesGetService(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
