/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsCreate } from "../../funcs/incidentsCreate.js";
import { CreateIncident$zodSchema } from "../../models/createincident.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateIncident$zodSchema,
};

export const tool$incidentsCreate: ToolDefinition<typeof args> = {
  name: "create-incident",
  description: `Create an incident

Create a new incident`,
  scopes: ["read", "write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
