/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsGetIncident } from "../../funcs/incidentsGetIncident.js";
import { GetIncidentRequest$zodSchema } from "../../models/getincidentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetIncidentRequest$zodSchema,
};

export const tool$incidentsGetIncident: ToolDefinition<typeof args> = {
  name: "get-incident",
  description:
    `Retrieves detailed information about a specific incident. This is useful for:

  - Getting incident details including affected services,
  - Viewing incident status, severity, and impact,
  - Finding services impacted by an incident,
  - Getting team assignments and other incident metadata.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsGetIncident(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
