/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e9cd940d0c0
 */

import { signalsGetTeamOnCallSchedule } from "../../funcs/signalsGetTeamOnCallSchedule.js";
import { GetTeamOnCallScheduleRequest$zodSchema } from "../../models/getteamoncallscheduleop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTeamOnCallScheduleRequest$zodSchema,
};

export const tool$signalsGetTeamOnCallSchedule: ToolDefinition<typeof args> = {
  name: "get-team-on-call-schedule",
  description:
    `Retrieves a specific on-call schedule for a team. This is useful for:

  - Getting detailed information about a specific schedule,
  - Viewing schedule rotations and members,
  - Checking schedule configuration.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await signalsGetTeamOnCallSchedule(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
