/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b70e6afee68f
 */

import { signalsListTeamOnCallSchedules } from "../../funcs/signalsListTeamOnCallSchedules.js";
import { ListTeamOnCallSchedulesRequest$zodSchema } from "../../models/listteamoncallschedulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTeamOnCallSchedulesRequest$zodSchema,
};

export const tool$signalsListTeamOnCallSchedules: ToolDefinition<typeof args> =
  {
    name: "list-team-on-call-schedules",
    description:
      `Lists all on-call schedules for a specific team. This is useful for:

  - Getting a list of on-call schedules for a team,
  - Finding available schedules to assign to incidents,
  - Viewing schedule configurations.
`,
    scopes: ["read"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await signalsListTeamOnCallSchedules(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
