/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsGetTeam } from "../../funcs/teamsGetTeam.js";
import { GetTeamRequest$zodSchema } from "../../models/getteamop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTeamRequest$zodSchema,
};

export const tool$teamsGetTeam: ToolDefinition<typeof args> = {
  name: "get-team",
  description:
    `Retrieves detailed information about a specific team, including its members. This is useful for:

  - Getting team details and configuration,
  - Viewing team members and memberships,
  - Finding users on a specific team,
  - Checking team assignments and roles.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teamsGetTeam(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
