/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 64244a778184
 */

import { teamsListTeams } from "../../funcs/teamsListTeams.js";
import { ListTeamsRequest$zodSchema } from "../../models/listteamsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTeamsRequest$zodSchema.optional(),
};

export const tool$teamsListTeams: ToolDefinition<typeof args> = {
  name: "list-teams",
  description: `Lists all teams in the organization. This is useful for:

  - Getting a list of all teams,
  - Finding team IDs for other operations,
  - Viewing team configurations.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teamsListTeams(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
