/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c3bf85668faa
 */

import { usersListUsers } from "../../funcs/usersListUsers.js";
import { ListUsersRequest$zodSchema } from "../../models/listusersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUsersRequest$zodSchema.optional(),
};

export const tool$usersListUsers: ToolDefinition<typeof args> = {
  name: "list-users",
  description: `Lists all users in the organization. This is useful for:

  - Getting a list of all users,
  - Finding user IDs for other operations,
  - Searching for users by name or email,
  - Viewing user information.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersListUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
