/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { FireHydrantCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { Register } from "./extensions.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { registerMCPExtensions } from "./server.extensions.js";
import { createRegisterTool } from "./tools.js";
import { tool$alertsList } from "./tools/alertsList.js";
import { tool$audiencesGetSummary } from "./tools/audiencesGetSummary.js";
import { tool$audiencesListSummaries } from "./tools/audiencesListSummaries.js";
import { tool$incidentsCreate } from "./tools/incidentsCreate.js";
import { tool$incidentsList } from "./tools/incidentsList.js";
import { tool$retrospectivesList } from "./tools/retrospectivesList.js";
import { tool$retrospectivesUpdateField } from "./tools/retrospectivesUpdateField.js";
import { tool$signalsGetTeamOnCallSchedule } from "./tools/signalsGetTeamOnCallSchedule.js";
import { tool$signalsListTeamOnCallSchedules } from "./tools/signalsListTeamOnCallSchedules.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => FireHydrantCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "FireHydrant",
    version: "0.2.1",
  });

  const getClient = deps.getSDK || (() =>
    new FireHydrantCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$signalsListTeamOnCallSchedules);
  tool(tool$signalsGetTeamOnCallSchedule);
  tool(tool$incidentsList);
  tool(tool$incidentsCreate);
  tool(tool$retrospectivesList);
  tool(tool$retrospectivesUpdateField);
  tool(tool$alertsList);
  tool(tool$audiencesGetSummary);
  tool(tool$audiencesListSummaries);

  registerMCPExtensions(register satisfies Register);

  return { server, tools };
}
