/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d92e04c6c89
 */

import * as z from "zod";

/**
 * AI_Entities_IncidentSummaryEntity model
 */
export type AIEntitiesIncidentSummaryEntity = {
  id?: string | null | undefined;
  content?: string | null | undefined;
  source_hash?: string | null | undefined;
  type?: string | null | undefined;
  created_at?: string | null | undefined;
  incident_updated_at?: string | null | undefined;
};

export const AIEntitiesIncidentSummaryEntity$zodSchema: z.ZodType<
  AIEntitiesIncidentSummaryEntity
> = z.object({
  content: z.string().nullable().optional(),
  created_at: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  incident_updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  source_hash: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
}).describe("AI_Entities_IncidentSummaryEntity model");
