/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The event's payload
 */
export type AlertsSirenEventEntityData = {};

export const AlertsSirenEventEntityData$zodSchema: z.ZodType<
  AlertsSirenEventEntityData
> = z.object({}).describe("The event's payload");

export type AlertsSirenEventEntity = {
  id?: string | null | undefined;
  type?: string | null | undefined;
  data?: AlertsSirenEventEntityData | null | undefined;
  created_at?: string | null | undefined;
};

export const AlertsSirenEventEntity$zodSchema: z.ZodType<
  AlertsSirenEventEntity
> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  data: z.lazy(() => AlertsSirenEventEntityData$zodSchema).nullable()
    .optional(),
  id: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
});
