/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AudiencesEntitiesDetailEntity = {
  id?: string | null | undefined;
  question?: string | null | undefined;
  prompt?: string | null | undefined;
  position?: number | null | undefined;
  slug?: string | null | undefined;
};

export const AudiencesEntitiesDetailEntity$zodSchema: z.ZodType<
  AudiencesEntitiesDetailEntity
> = z.object({
  id: z.string().nullable().optional(),
  position: z.int().nullable().optional(),
  prompt: z.string().nullable().optional(),
  question: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
});
