/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5888dad5b6a2
 */

import * as z from "zod";
import {
  AudiencesEntitiesAudienceEntity,
  AudiencesEntitiesAudienceEntity$zodSchema,
} from "./audiencesentitiesaudienceentity.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";

/**
 * Audiences_Entities_AudienceEntityPaginated model
 */
export type AudiencesEntitiesAudienceEntityPaginated = {
  data?: Array<AudiencesEntitiesAudienceEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const AudiencesEntitiesAudienceEntityPaginated$zodSchema: z.ZodType<
  AudiencesEntitiesAudienceEntityPaginated
> = z.object({
  data: z.array(AudiencesEntitiesAudienceEntity$zodSchema).nullable()
    .optional(),
  pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
}).describe("Audiences_Entities_AudienceEntityPaginated model");
