/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c245db680d47
 */

import * as z from "zod";
import {
  AudiencesEntitiesDetailEntity,
  AudiencesEntitiesDetailEntity$zodSchema,
} from "./audiencesentitiesdetailentity.js";

/**
 * Audiences_Entities_AudienceEntity model
 */
export type AudiencesEntitiesAudienceEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  description?: string | null | undefined;
  default?: boolean | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  discarded_at?: string | null | undefined;
  details?: Array<AudiencesEntitiesDetailEntity> | null | undefined;
};

export const AudiencesEntitiesAudienceEntity$zodSchema: z.ZodType<
  AudiencesEntitiesAudienceEntity
> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  default: z.boolean().nullable().optional(),
  description: z.string().nullable().optional(),
  details: z.array(AudiencesEntitiesDetailEntity$zodSchema).nullable()
    .optional(),
  discarded_at: z.iso.datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("Audiences_Entities_AudienceEntity model");
