/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d9baa0c7e88a
 */

import * as z from "zod";

/**
 * Audiences_Entities_AudienceSummariesEntity model
 */
export type AudiencesEntitiesAudienceSummariesEntity = {
  incident_id?: string | null | undefined;
  audiences?: string | null | undefined;
};

export const AudiencesEntitiesAudienceSummariesEntity$zodSchema: z.ZodType<
  AudiencesEntitiesAudienceSummariesEntity
> = z.object({
  audiences: z.string().nullable().optional(),
  incident_id: z.string().nullable().optional(),
}).describe("Audiences_Entities_AudienceSummariesEntity model");
