/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChecklistCheckEntity,
  ChecklistCheckEntity$zodSchema,
} from "./checklistcheckentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";
import {
  ServiceEntityChecklist,
  ServiceEntityChecklist$zodSchema,
} from "./serviceentitychecklist.js";

/**
 * ChecklistTemplateEntity model
 */
export type ChecklistTemplateEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  checks?: Array<ChecklistCheckEntity> | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  connected_services?: Array<ServiceEntityChecklist> | null | undefined;
};

export const ChecklistTemplateEntity$zodSchema: z.ZodType<
  ChecklistTemplateEntity
> = z.object({
  checks: z.array(ChecklistCheckEntity$zodSchema).nullable().optional(),
  connected_services: z.array(ServiceEntityChecklist$zodSchema).nullable()
    .optional(),
  created_at: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("ChecklistTemplateEntity model");
