/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c2c93d4c0b1e
 */

import * as z from "zod";

export type ChecklistCheckEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  status?: boolean | null | undefined;
};

export const ChecklistCheckEntity$zodSchema: z.ZodType<ChecklistCheckEntity> = z
  .object({
    description: z.string().nullable().optional(),
    id: z.string().nullable().optional(),
    name: z.string().nullable().optional(),
    status: z.boolean().nullable().optional(),
  });
