/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5d56d9eaaa8d
 */

import * as z from "zod";
import { IncidentEntity, IncidentEntity$zodSchema } from "./incidententity.js";

export type CreateIncidentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  IncidentEntity?: IncidentEntity | undefined;
};

export const CreateIncidentResponse$zodSchema: z.ZodType<
  CreateIncidentResponse
> = z.object({
  ContentType: z.string(),
  IncidentEntity: IncidentEntity$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
