/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f48a32c283e5
 */

import * as z from "zod";
import {
  ExternalResourceEntity,
  ExternalResourceEntity$zodSchema,
} from "./externalresourceentity.js";
import {
  FunctionalityEntityLite,
  FunctionalityEntityLite$zodSchema,
} from "./functionalityentitylite.js";
import {
  ServiceEntityLite,
  ServiceEntityLite$zodSchema,
} from "./serviceentitylite.js";

/**
 * EnvironmentEntryEntity model
 */
export type EnvironmentEntryEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  description?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  active_incidents?: Array<string> | null | undefined;
  external_resources?: Array<ExternalResourceEntity> | null | undefined;
  functionalities?: Array<FunctionalityEntityLite> | null | undefined;
  services?: Array<ServiceEntityLite> | null | undefined;
};

export const EnvironmentEntryEntity$zodSchema: z.ZodType<
  EnvironmentEntryEntity
> = z.object({
  active_incidents: z.array(z.string()).nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  external_resources: z.array(ExternalResourceEntity$zodSchema).nullable()
    .optional(),
  functionalities: z.array(FunctionalityEntityLite$zodSchema).nullable()
    .optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  services: z.array(ServiceEntityLite$zodSchema).nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("EnvironmentEntryEntity model");
