/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8063802c48a8
 */

import * as z from "zod";

export type ExternalResourceEntity = {
  connection_type?: string | null | undefined;
  connection_name?: string | null | undefined;
  connection_full_favicon_url?: string | null | undefined;
  connection_id?: string | null | undefined;
  remote_id?: string | null | undefined;
  remote_url?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  name?: string | null | undefined;
};

export const ExternalResourceEntity$zodSchema: z.ZodType<
  ExternalResourceEntity
> = z.object({
  connection_full_favicon_url: z.string().nullable().optional(),
  connection_id: z.string().nullable().optional(),
  connection_name: z.string().nullable().optional(),
  connection_type: z.string().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  name: z.string().nullable().optional(),
  remote_id: z.string().nullable().optional(),
  remote_url: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
});
