/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EnvironmentEntryEntity,
  EnvironmentEntryEntity$zodSchema,
} from "./environmententryentity.js";
import {
  ExternalResourceEntity,
  ExternalResourceEntity$zodSchema,
} from "./externalresourceentity.js";
import { LinksEntity, LinksEntity$zodSchema } from "./linksentity.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";
import {
  ServiceEntityLite,
  ServiceEntityLite$zodSchema,
} from "./serviceentitylite.js";
import { TeamEntityLite, TeamEntityLite$zodSchema } from "./teamentitylite.js";

/**
 * FunctionalityEntity model
 */
export type FunctionalityEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  description?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  labels?: { [k: string]: any } | null | undefined;
  active_incidents?: Array<string> | null | undefined;
  links?: Array<LinksEntity> | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  service_tier?: number | null | undefined;
  alert_on_add?: boolean | null | undefined;
  auto_add_responding_team?: boolean | null | undefined;
  updated_by?: NullableAuthorEntity | null | undefined;
  services?: Array<ServiceEntityLite> | null | undefined;
  environments?: Array<EnvironmentEntryEntity> | null | undefined;
  external_resources?: Array<ExternalResourceEntity> | null | undefined;
  teams?: Array<TeamEntityLite> | null | undefined;
};

export const FunctionalityEntity$zodSchema: z.ZodType<FunctionalityEntity> = z
  .object({
    active_incidents: z.array(z.string()).nullable().optional(),
    alert_on_add: z.boolean().nullable().optional(),
    auto_add_responding_team: z.boolean().nullable().optional(),
    created_at: z.iso.datetime({ offset: true }).nullable().optional(),
    description: z.string().nullable().optional(),
    environments: z.array(EnvironmentEntryEntity$zodSchema).nullable()
      .optional(),
    external_resources: z.array(ExternalResourceEntity$zodSchema).nullable()
      .optional(),
    id: z.string().nullable().optional(),
    labels: z.record(z.string(), z.any()).nullable().optional(),
    links: z.array(LinksEntity$zodSchema).nullable().optional(),
    name: z.string().nullable().optional(),
    owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
    service_tier: z.int().nullable().optional(),
    services: z.array(ServiceEntityLite$zodSchema).nullable().optional(),
    slug: z.string().nullable().optional(),
    teams: z.array(TeamEntityLite$zodSchema).nullable().optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
    updated_by: NullableAuthorEntity$zodSchema.nullable().optional(),
  }).describe("FunctionalityEntity model");
