/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ac7e14aff7bd
 */

import * as z from "zod";
import { LinksEntity, LinksEntity$zodSchema } from "./linksentity.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";

export type FunctionalityEntityLite = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  description?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  labels?: { [k: string]: any } | null | undefined;
  active_incidents?: Array<string> | null | undefined;
  links?: Array<LinksEntity> | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  service_tier?: number | null | undefined;
  alert_on_add?: boolean | null | undefined;
  auto_add_responding_team?: boolean | null | undefined;
  updated_by?: NullableAuthorEntity | null | undefined;
};

export const FunctionalityEntityLite$zodSchema: z.ZodType<
  FunctionalityEntityLite
> = z.object({
  active_incidents: z.array(z.string()).nullable().optional(),
  alert_on_add: z.boolean().nullable().optional(),
  auto_add_responding_team: z.boolean().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  labels: z.record(z.string(), z.any()).nullable().optional(),
  links: z.array(LinksEntity$zodSchema).nullable().optional(),
  name: z.string().nullable().optional(),
  owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
  service_tier: z.int().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  updated_by: NullableAuthorEntity$zodSchema.nullable().optional(),
});
