/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1132b3ed445b
 */

import * as z from "zod";
import {
  AudiencesEntitiesAudienceEntity,
  AudiencesEntitiesAudienceEntity$zodSchema,
} from "./audiencesentitiesaudienceentity.js";

export type GetAudienceRequest = { audience_id: string };

export const GetAudienceRequest$zodSchema: z.ZodType<GetAudienceRequest> = z
  .object({
    audience_id: z.string().describe("Unique identifier of the audience"),
  });

export type GetAudienceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Audiences_Entities_AudienceEntity?:
    | AudiencesEntitiesAudienceEntity
    | undefined;
};

export const GetAudienceResponse$zodSchema: z.ZodType<GetAudienceResponse> = z
  .object({
    Audiences_Entities_AudienceEntity: AudiencesEntitiesAudienceEntity$zodSchema
      .optional(),
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
  });
