/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 357d90593355
 */

import * as z from "zod";
import {
  AIEntitiesIncidentSummaryEntity,
  AIEntitiesIncidentSummaryEntity$zodSchema,
} from "./aientitiesincidentsummaryentity.js";

export type GetAudienceSummaryRequest = {
  audience_id: string;
  incident_id: string;
};

export const GetAudienceSummaryRequest$zodSchema: z.ZodType<
  GetAudienceSummaryRequest
> = z.object({
  audience_id: z.string().describe("Unique identifier of the audience"),
  incident_id: z.string().describe(
    "Unique identifier of the incident to summarize",
  ),
});

export type GetAudienceSummaryResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  AI_Entities_IncidentSummaryEntity?:
    | AIEntitiesIncidentSummaryEntity
    | undefined;
};

export const GetAudienceSummaryResponse$zodSchema: z.ZodType<
  GetAudienceSummaryResponse
> = z.object({
  AI_Entities_IncidentSummaryEntity: AIEntitiesIncidentSummaryEntity$zodSchema
    .optional(),
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
