/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IncidentEntity, IncidentEntity$zodSchema } from "./incidententity.js";

export type GetIncidentRequest = { incident_id: string };

export const GetIncidentRequest$zodSchema: z.ZodType<GetIncidentRequest> = z
  .object({
    incident_id: z.string(),
  });

export type GetIncidentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  IncidentEntity?: IncidentEntity | undefined;
};

export const GetIncidentResponse$zodSchema: z.ZodType<GetIncidentResponse> = z
  .object({
    ContentType: z.string(),
    IncidentEntity: IncidentEntity$zodSchema.optional(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
  });
