/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1edccc2d7fd4
 */

import * as z from "zod";
import { ServiceEntity, ServiceEntity$zodSchema } from "./serviceentity.js";

export type GetServiceRequest = { service_id: string };

export const GetServiceRequest$zodSchema: z.ZodType<GetServiceRequest> = z
  .object({
    service_id: z.string(),
  });

export type GetServiceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ServiceEntity?: ServiceEntity | undefined;
};

export const GetServiceResponse$zodSchema: z.ZodType<GetServiceResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    ServiceEntity: ServiceEntity$zodSchema.optional(),
    StatusCode: z.int(),
  });
