/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55cead450ca9
 */

import * as z from "zod";
import { TeamEntity, TeamEntity$zodSchema } from "./teamentity.js";

export type GetTeamRequest = {
  team_id: string;
  lite?: boolean | null | undefined;
};

export const GetTeamRequest$zodSchema: z.ZodType<GetTeamRequest> = z.object({
  lite: z.boolean().describe(
    "Boolean to determine whether to return a slimified version of the teams object",
  ).nullable().optional(),
  team_id: z.string(),
});

export type GetTeamResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  TeamEntity?: TeamEntity | undefined;
};

export const GetTeamResponse$zodSchema: z.ZodType<GetTeamResponse> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  TeamEntity: TeamEntity$zodSchema.optional(),
});
