/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3e2ae7be9b75
 */

import * as z from "zod";
import {
  SignalsAPIOnCallScheduleEntity,
  SignalsAPIOnCallScheduleEntity$zodSchema,
} from "./signalsapioncallscheduleentity.js";

export type GetTeamOnCallScheduleRequest = {
  team_id: string;
  schedule_id: string;
  shift_time_window_start?: string | null | undefined;
  shift_time_window_end?: string | null | undefined;
};

export const GetTeamOnCallScheduleRequest$zodSchema: z.ZodType<
  GetTeamOnCallScheduleRequest
> = z.object({
  schedule_id: z.string(),
  shift_time_window_end: z.string().describe(
    "An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window.. If provided, only shifts that start at or before this time will be included.",
  ).nullable().optional(),
  shift_time_window_start: z.string().describe(
    "An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window. If provided, only shifts that end at or after this time will be included.",
  ).nullable().optional(),
  team_id: z.string(),
});

export type GetTeamOnCallScheduleResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Signals_API_OnCallScheduleEntity?: SignalsAPIOnCallScheduleEntity | undefined;
};

export const GetTeamOnCallScheduleResponse$zodSchema: z.ZodType<
  GetTeamOnCallScheduleResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  Signals_API_OnCallScheduleEntity: SignalsAPIOnCallScheduleEntity$zodSchema
    .optional(),
  StatusCode: z.int(),
});
