/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableImportsImportErrorEntityResourceEntity,
  NullableImportsImportErrorEntityResourceEntity$zodSchema,
} from "./nullableimportsimporterrorentityresourceentity.js";

/**
 * Additional error data
 */
export type ImportsImportErrorEntityData = {};

export const ImportsImportErrorEntityData$zodSchema: z.ZodType<
  ImportsImportErrorEntityData
> = z.object({}).describe("Additional error data");

export type ImportsImportErrorEntity = {
  id?: string | null | undefined;
  message?: string | null | undefined;
  created_at?: string | null | undefined;
  data?: ImportsImportErrorEntityData | null | undefined;
  resource?: NullableImportsImportErrorEntityResourceEntity | null | undefined;
};

export const ImportsImportErrorEntity$zodSchema: z.ZodType<
  ImportsImportErrorEntity
> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  data: z.lazy(() => ImportsImportErrorEntityData$zodSchema).nullable()
    .optional(),
  id: z.string().nullable().optional(),
  message: z.string().nullable().optional(),
  resource: NullableImportsImportErrorEntityResourceEntity$zodSchema.nullable()
    .optional(),
});
