/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a297d40be95
 */

import * as z from "zod";

export type IncidentsRetrospectiveEntitySectionEntity = {
  slug?: string | null | undefined;
  elements?: Array<string> | null | undefined;
};

export const IncidentsRetrospectiveEntitySectionEntity$zodSchema: z.ZodType<
  IncidentsRetrospectiveEntitySectionEntity
> = z.object({
  elements: z.array(z.string()).nullable().optional(),
  slug: z.string().nullable().optional(),
});
