/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c87997a8e8d5
 */

import * as z from "zod";

export type LinksEntity = {
  id?: string | null | undefined;
  href_url?: string | null | undefined;
  icon_url?: string | null | undefined;
  name?: string | null | undefined;
};

export const LinksEntity$zodSchema: z.ZodType<LinksEntity> = z.object({
  href_url: z.string().nullable().optional(),
  icon_url: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
});
