/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AudiencesEntitiesAudienceSummariesEntity,
  AudiencesEntitiesAudienceSummariesEntity$zodSchema,
} from "./audiencesentitiesaudiencesummariesentity.js";

export type ListAudienceSummariesRequest = { incident_id: string };

export const ListAudienceSummariesRequest$zodSchema: z.ZodType<
  ListAudienceSummariesRequest
> = z.object({
  incident_id: z.string().describe(
    "Unique identifier of the incident to summarize",
  ),
});

export type ListAudienceSummariesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Audiences_Entities_AudienceSummariesEntity?:
    | AudiencesEntitiesAudienceSummariesEntity
    | undefined;
};

export const ListAudienceSummariesResponse$zodSchema: z.ZodType<
  ListAudienceSummariesResponse
> = z.object({
  Audiences_Entities_AudienceSummariesEntity:
    AudiencesEntitiesAudienceSummariesEntity$zodSchema.optional(),
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
