/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93a2b66f4ea9
 */

import * as z from "zod";
import {
  AudiencesEntitiesAudienceEntityPaginated,
  AudiencesEntitiesAudienceEntityPaginated$zodSchema,
} from "./audiencesentitiesaudienceentitypaginated.js";

export type ListAudiencesRequest = {
  include_archived?: boolean | null | undefined;
};

export const ListAudiencesRequest$zodSchema: z.ZodType<ListAudiencesRequest> = z
  .object({
    include_archived: z.boolean().default(false).describe(
      "Include archived (discarded) audiences",
    ).nullable(),
  });

export type ListAudiencesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Audiences_Entities_AudienceEntityPaginated?:
    | AudiencesEntitiesAudienceEntityPaginated
    | undefined;
};

export const ListAudiencesResponse$zodSchema: z.ZodType<ListAudiencesResponse> =
  z.object({
    Audiences_Entities_AudienceEntityPaginated:
      AudiencesEntitiesAudienceEntityPaginated$zodSchema.optional(),
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
  });
