/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6a44e1a78976
 */

import * as z from "zod";
import {
  IncidentsRetrospectiveEntityPaginated,
  IncidentsRetrospectiveEntityPaginated$zodSchema,
} from "./incidentsretrospectiveentitypaginated.js";

export type ListIncidentRetrospectivesRequest = {
  page?: number | null | undefined;
  per_page?: number | null | undefined;
  is_hidden?: boolean | null | undefined;
  incident_id: string;
};

export const ListIncidentRetrospectivesRequest$zodSchema: z.ZodType<
  ListIncidentRetrospectivesRequest
> = z.object({
  incident_id: z.string(),
  is_hidden: z.boolean().describe("Filter by hidden status.").nullable()
    .optional(),
  page: z.int().nullable().optional(),
  per_page: z.int().nullable().optional(),
});

export type ListIncidentRetrospectivesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Incidents_RetrospectiveEntityPaginated?:
    | IncidentsRetrospectiveEntityPaginated
    | undefined;
};

export const ListIncidentRetrospectivesResponse$zodSchema: z.ZodType<
  ListIncidentRetrospectivesResponse
> = z.object({
  ContentType: z.string(),
  Incidents_RetrospectiveEntityPaginated:
    IncidentsRetrospectiveEntityPaginated$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
