/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UserEntityPaginated,
  UserEntityPaginated$zodSchema,
} from "./userentitypaginated.js";

export type ListUsersRequest = {
  page?: number | null | undefined;
  per_page?: number | null | undefined;
  query?: string | null | undefined;
  name?: string | null | undefined;
};

export const ListUsersRequest$zodSchema: z.ZodType<ListUsersRequest> = z.object(
  {
    name: z.string().describe("Text string of a query to filter users by name")
      .nullable().optional(),
    page: z.int().nullable().optional(),
    per_page: z.int().nullable().optional(),
    query: z.string().describe(
      "Text string of a query to filter users by name or email",
    ).nullable().optional(),
  },
);

export type ListUsersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  UserEntityPaginated?: UserEntityPaginated | undefined;
};

export const ListUsersResponse$zodSchema: z.ZodType<ListUsersResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    UserEntityPaginated: UserEntityPaginated$zodSchema.optional(),
  });
