/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8c7884022d7d
 */

import * as z from "zod";
import {
  SignalsAPIOnCallScheduleEntityPaginated,
  SignalsAPIOnCallScheduleEntityPaginated$zodSchema,
} from "./signalsapioncallscheduleentitypaginated.js";

export type ListTeamOnCallSchedulesRequest = {
  team_id: string;
  shift_time_window_start?: string | null | undefined;
  shift_time_window_end?: string | null | undefined;
  query?: string | null | undefined;
  page?: number | null | undefined;
  per_page?: number | null | undefined;
};

export const ListTeamOnCallSchedulesRequest$zodSchema: z.ZodType<
  ListTeamOnCallSchedulesRequest
> = z.object({
  page: z.int().nullable().optional(),
  per_page: z.int().nullable().optional(),
  query: z.string().describe(
    "A query string for searching through the list of on-call schedules.",
  ).nullable().optional(),
  shift_time_window_end: z.string().describe(
    "An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window.. If provided, only shifts that start at or before this time will be included.",
  ).nullable().optional(),
  shift_time_window_start: z.string().describe(
    "An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window. If provided, only shifts that end at or after this time will be included.",
  ).nullable().optional(),
  team_id: z.string(),
});

export type ListTeamOnCallSchedulesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Signals_API_OnCallScheduleEntityPaginated?:
    | SignalsAPIOnCallScheduleEntityPaginated
    | undefined;
};

export const ListTeamOnCallSchedulesResponse$zodSchema: z.ZodType<
  ListTeamOnCallSchedulesResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  Signals_API_OnCallScheduleEntityPaginated:
    SignalsAPIOnCallScheduleEntityPaginated$zodSchema.optional(),
  StatusCode: z.int(),
});
