/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d57a4aa28fd
 */

import * as z from "zod";
import {
  TeamEntityPaginated,
  TeamEntityPaginated$zodSchema,
} from "./teamentitypaginated.js";

export type ListTeamsRequest = {
  page?: number | null | undefined;
  per_page?: number | null | undefined;
  query?: string | null | undefined;
  name?: string | null | undefined;
  services?: string | null | undefined;
  default_incident_role?: string | null | undefined;
  lite?: boolean | null | undefined;
};

export const ListTeamsRequest$zodSchema: z.ZodType<ListTeamsRequest> = z.object(
  {
    default_incident_role: z.string().describe(
      "Filter by teams that have or do not have members with a default incident role asssigned. Value may be 'present', 'blank', or the ID of an incident role.",
    ).nullable().optional(),
    lite: z.boolean().describe(
      "Boolean to determine whether to return a slimified version of the teams object",
    ).nullable().optional(),
    name: z.string().describe("A query to search teams by their name")
      .nullable().optional(),
    page: z.int().nullable().optional(),
    per_page: z.int().nullable().optional(),
    query: z.string().describe(
      "A query to search teams by their name or description",
    ).nullable().optional(),
    services: z.string().describe("A comma separated list of service IDs")
      .nullable().optional(),
  },
);

export type ListTeamsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  TeamEntityPaginated?: TeamEntityPaginated | undefined;
};

export const ListTeamsResponse$zodSchema: z.ZodType<ListTeamsResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    TeamEntityPaginated: TeamEntityPaginated$zodSchema.optional(),
  });
