/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableIncidentRoleEntity,
  NullableIncidentRoleEntity$zodSchema,
} from "./nullableincidentroleentity.js";
import {
  NullableScheduleEntity,
  NullableScheduleEntity$zodSchema,
} from "./nullablescheduleentity.js";
import {
  NullableSuccinctEntity,
  NullableSuccinctEntity$zodSchema,
} from "./nullablesuccinctentity.js";
import {
  NullableUserEntity,
  NullableUserEntity$zodSchema,
} from "./nullableuserentity.js";

export type MembershipEntity = {
  user?: NullableUserEntity | null | undefined;
  schedule?: NullableScheduleEntity | null | undefined;
  signals_on_call_schedule?: NullableSuccinctEntity | null | undefined;
  default_incident_role?: NullableIncidentRoleEntity | null | undefined;
};

export const MembershipEntity$zodSchema: z.ZodType<MembershipEntity> = z.object(
  {
    default_incident_role: NullableIncidentRoleEntity$zodSchema.nullable()
      .optional(),
    schedule: NullableScheduleEntity$zodSchema.nullable().optional(),
    signals_on_call_schedule: NullableSuccinctEntity$zodSchema.nullable()
      .optional(),
    user: NullableUserEntity$zodSchema.nullable().optional(),
  },
);
