/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9dd68eb3bd1e
 */

import * as z from "zod";

export type NullableSuccinctEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
};

export const NullableSuccinctEntity$zodSchema: z.ZodType<
  NullableSuccinctEntity
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
});
