/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableSignalsAPIOnCallStrategyEntity = {
  type?: string | null | undefined;
  handoff_time?: string | null | undefined;
  handoff_day?: string | null | undefined;
  shift_duration?: string | null | undefined;
};

export const NullableSignalsAPIOnCallStrategyEntity$zodSchema: z.ZodType<
  NullableSignalsAPIOnCallStrategyEntity
> = z.object({
  handoff_day: z.string().nullable().optional(),
  handoff_time: z.string().nullable().optional(),
  shift_duration: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
});
