/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9dd3300db7e0
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ImportsImportErrorEntity,
  ImportsImportErrorEntity$zodSchema,
} from "./importsimporterrorentity.js";

export const NullableImportsImportableResourceEntityState = {
  Selected: "selected",
  Skipped: "skipped",
  Imported: "imported",
  Errored: "errored",
} as const;
export type NullableImportsImportableResourceEntityState = ClosedEnum<
  typeof NullableImportsImportableResourceEntityState
>;

export const NullableImportsImportableResourceEntityState$zodSchema = z.enum([
  "selected",
  "skipped",
  "imported",
  "errored",
]);

export type NullableImportsImportableResourceEntity = {
  import_errors?: Array<ImportsImportErrorEntity> | null | undefined;
  imported_at?: string | null | undefined;
  remote_id?: string | null | undefined;
  state?: NullableImportsImportableResourceEntityState | null | undefined;
};

export const NullableImportsImportableResourceEntity$zodSchema: z.ZodType<
  NullableImportsImportableResourceEntity
> = z.object({
  import_errors: z.array(ImportsImportErrorEntity$zodSchema).nullable()
    .optional(),
  imported_at: z.iso.datetime({ offset: true }).nullable().optional(),
  remote_id: z.string().nullable().optional(),
  state: NullableImportsImportableResourceEntityState$zodSchema.nullable()
    .optional(),
});
