/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3ff2b022f633
 */

import * as z from "zod";

export type NullablePublicApiv1IncidentsSuccinctEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  number?: number | null | undefined;
};

export const NullablePublicApiv1IncidentsSuccinctEntity$zodSchema: z.ZodType<
  NullablePublicApiv1IncidentsSuccinctEntity
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  number: z.int().nullable().optional(),
});
