/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bfe1241fe979
 */

import * as z from "zod";
import {
  NullableFHTypesGenericEntity,
  NullableFHTypesGenericEntity$zodSchema,
} from "./nullablefhtypesgenericentity.js";

/**
 * An unstructured object of key/value pairs describing the logic for applying the rule.
 */
export type Logic = {};

export const Logic$zodSchema: z.ZodType<Logic> = z.object({}).describe(
  "An unstructured object of key/value pairs describing the logic for applying the rule.",
);

export type NullableRulesRuleEntity = {
  logic?: Logic | null | undefined;
  user_data?: NullableFHTypesGenericEntity | null | undefined;
};

export const NullableRulesRuleEntity$zodSchema: z.ZodType<
  NullableRulesRuleEntity
> = z.object({
  logic: z.lazy(() => Logic$zodSchema).nullable().optional(),
  user_data: NullableFHTypesGenericEntity$zodSchema.nullable().optional(),
});
