/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f7a9c8311198
 */

import * as z from "zod";

export type NullablePaginationEntity = {
  count?: number | null | undefined;
  page?: number | null | undefined;
  items?: number | null | undefined;
  pages?: number | null | undefined;
  last?: number | null | undefined;
  prev?: number | null | undefined;
  next?: number | null | undefined;
};

export const NullablePaginationEntity$zodSchema: z.ZodType<
  NullablePaginationEntity
> = z.object({
  count: z.int().nullable().optional(),
  items: z.int().nullable().optional(),
  last: z.int().nullable().optional(),
  next: z.int().nullable().optional(),
  page: z.int().nullable().optional(),
  pages: z.int().nullable().optional(),
  prev: z.int().nullable().optional(),
});
