/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Ticketing_PriorityEntity model
 */
export type NullableTicketingPriorityEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  position?: number | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
};

export const NullableTicketingPriorityEntity$zodSchema: z.ZodType<
  NullableTicketingPriorityEntity
> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  position: z.int().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("Ticketing_PriorityEntity model");
