/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c5d234abc2b0
 */

import * as z from "zod";

export type NullableAuthorEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  source?: string | null | undefined;
  email?: string | null | undefined;
};

export const NullableAuthorEntity$zodSchema: z.ZodType<NullableAuthorEntity> = z
  .object({
    email: z.string().nullable().optional(),
    id: z.string().nullable().optional(),
    name: z.string().nullable().optional(),
    source: z.string().nullable().optional(),
  });
