/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d9a42ee5c87
 */

import * as z from "zod";

export type NullableOrganizationEntity = {
  name?: string | null | undefined;
  id?: string | null | undefined;
};

export const NullableOrganizationEntity$zodSchema: z.ZodType<
  NullableOrganizationEntity
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
});
