/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 461bcd7d30fe
 */

import * as z from "zod";
import {
  NullableIncidentEntity,
  NullableIncidentEntity$zodSchema,
} from "./nullableincidententity.js";

export type NullableIntegrationsMicrosoftTeamsV2ChannelEntity = {
  id?: string | null | undefined;
  channel_id?: string | null | undefined;
  channel_name?: string | null | undefined;
  ms_team_id?: string | null | undefined;
  team_name?: string | null | undefined;
  channel_url?: string | null | undefined;
  status?: string | null | undefined;
  incident?: NullableIncidentEntity | null | undefined;
};

export const NullableIntegrationsMicrosoftTeamsV2ChannelEntity$zodSchema:
  z.ZodType<NullableIntegrationsMicrosoftTeamsV2ChannelEntity> = z.object({
    channel_id: z.string().nullable().optional(),
    channel_name: z.string().nullable().optional(),
    channel_url: z.string().nullable().optional(),
    id: z.string().nullable().optional(),
    incident: NullableIncidentEntity$zodSchema.nullable().optional(),
    ms_team_id: z.string().nullable().optional(),
    status: z.string().nullable().optional(),
    team_name: z.string().nullable().optional(),
  });
