/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fdaa4d1508e2
 */

import * as z from "zod";

/**
 * IncidentRoleEntity model
 */
export type NullableIncidentRoleEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  discarded_at?: string | null | undefined;
};

export const NullableIncidentRoleEntity$zodSchema: z.ZodType<
  NullableIncidentRoleEntity
> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  discarded_at: z.iso.datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  summary: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("IncidentRoleEntity model");
