/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableFHTypesGenericEntity = {
  type?: string | null | undefined;
  value?: string | null | undefined;
  label?: string | null | undefined;
};

export const NullableFHTypesGenericEntity$zodSchema: z.ZodType<
  NullableFHTypesGenericEntity
> = z.object({
  label: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
  value: z.string().nullable().optional(),
});
