/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableIntegrationsSlackSlackChannelEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  slack_channel_id?: string | null | undefined;
};

export const NullableIntegrationsSlackSlackChannelEntity$zodSchema: z.ZodType<
  NullableIntegrationsSlackSlackChannelEntity
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  slack_channel_id: z.string().nullable().optional(),
});
