/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableScheduleEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  integration?: string | null | undefined;
  discarded?: boolean | null | undefined;
};

export const NullableScheduleEntity$zodSchema: z.ZodType<
  NullableScheduleEntity
> = z.object({
  discarded: z.boolean().nullable().optional(),
  id: z.string().nullable().optional(),
  integration: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
});
