/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableImportsImportErrorEntityResourceEntity = {
  resource_id?: string | null | undefined;
  resource_type?: string | null | undefined;
  name?: string | null | undefined;
};

export const NullableImportsImportErrorEntityResourceEntity$zodSchema:
  z.ZodType<NullableImportsImportErrorEntityResourceEntity> = z.object({
    name: z.string().nullable().optional(),
    resource_id: z.string().nullable().optional(),
    resource_type: z.string().nullable().optional(),
  });
