/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 42b9d005ec09
 */

import * as z from "zod";

export type NullableConversationsAPIEntitiesChannel = {
  name?: string | null | undefined;
};

export const NullableConversationsAPIEntitiesChannel$zodSchema: z.ZodType<
  NullableConversationsAPIEntitiesChannel
> = z.object({
  name: z.string().nullable().optional(),
});
