/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 60d4b6dde88a
 */

import * as z from "zod";

export type PublicApiv1IncidentsSuccinctEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  number?: number | null | undefined;
};

export const PublicApiv1IncidentsSuccinctEntity$zodSchema: z.ZodType<
  PublicApiv1IncidentsSuccinctEntity
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  number: z.int().nullable().optional(),
});
