/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 35f7e16e8510
 */

import * as z from "zod";

/**
 * ServiceEntityLite model
 */
export type ServiceEntityLite = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  service_tier?: number | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  allowed_params?: Array<string> | null | undefined;
  labels?: { [k: string]: any } | null | undefined;
  alert_on_add?: boolean | null | undefined;
  auto_add_responding_team?: boolean | null | undefined;
};

export const ServiceEntityLite$zodSchema: z.ZodType<ServiceEntityLite> = z
  .object({
    alert_on_add: z.boolean().nullable().optional(),
    allowed_params: z.array(z.string()).nullable().optional(),
    auto_add_responding_team: z.boolean().nullable().optional(),
    created_at: z.iso.datetime({ offset: true }).nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string().nullable().optional(),
    labels: z.record(z.string(), z.any()).nullable().optional(),
    name: z.string().nullable().optional(),
    service_tier: z.int().nullable().optional(),
    slug: z.string().nullable().optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  }).describe("ServiceEntityLite model");
