/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2ee3e888a98d
 */

import * as z from "zod";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";

export type ServiceEntityChecklist = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  service_tier?: number | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  allowed_params?: Array<string> | null | undefined;
  labels?: { [k: string]: any } | null | undefined;
  alert_on_add?: boolean | null | undefined;
  auto_add_responding_team?: boolean | null | undefined;
  completed_checks?: number | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  service_checklist_updated_at?: string | null | undefined;
};

export const ServiceEntityChecklist$zodSchema: z.ZodType<
  ServiceEntityChecklist
> = z.object({
  alert_on_add: z.boolean().nullable().optional(),
  allowed_params: z.array(z.string()).nullable().optional(),
  auto_add_responding_team: z.boolean().nullable().optional(),
  completed_checks: z.int().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  labels: z.record(z.string(), z.any()).nullable().optional(),
  name: z.string().nullable().optional(),
  owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
  service_checklist_updated_at: z.iso.datetime({ offset: true }).nullable()
    .optional(),
  service_tier: z.int().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
});
