/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a89cd377953a
 */

import * as z from "zod";
import {
  ChecklistTemplateEntity,
  ChecklistTemplateEntity$zodSchema,
} from "./checklisttemplateentity.js";
import {
  EnvironmentEntryEntity,
  EnvironmentEntryEntity$zodSchema,
} from "./environmententryentity.js";
import {
  ExternalResourceEntity,
  ExternalResourceEntity$zodSchema,
} from "./externalresourceentity.js";
import {
  FunctionalityEntity,
  FunctionalityEntity$zodSchema,
} from "./functionalityentity.js";
import { LinksEntity, LinksEntity$zodSchema } from "./linksentity.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";
import {
  NullableImportsImportableResourceEntity,
  NullableImportsImportableResourceEntity$zodSchema,
} from "./nullableimportsimportableresourceentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";
import { TeamEntityLite, TeamEntityLite$zodSchema } from "./teamentitylite.js";

/**
 * Indicates the settings of the catalog that manages this service
 */
export type ManagedBySettings = {};

export const ManagedBySettings$zodSchema: z.ZodType<ManagedBySettings> = z
  .object({}).describe(
    "Indicates the settings of the catalog that manages this service",
  );

/**
 * ServiceEntity model
 */
export type ServiceEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  service_tier?: number | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  allowed_params?: Array<string> | null | undefined;
  labels?: { [k: string]: any } | null | undefined;
  alert_on_add?: boolean | null | undefined;
  auto_add_responding_team?: boolean | null | undefined;
  active_incidents?: Array<string> | null | undefined;
  checklists?: Array<ChecklistTemplateEntity> | null | undefined;
  completed_checks?: number | null | undefined;
  external_resources?: Array<ExternalResourceEntity> | null | undefined;
  functionalities?: Array<FunctionalityEntity> | null | undefined;
  environments?: Array<EnvironmentEntryEntity> | null | undefined;
  last_import?: NullableImportsImportableResourceEntity | null | undefined;
  links?: Array<LinksEntity> | null | undefined;
  managed_by?: string | null | undefined;
  managed_by_settings?: ManagedBySettings | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  service_checklist_updated_at?: string | null | undefined;
  teams?: Array<TeamEntityLite> | null | undefined;
  updated_by?: NullableAuthorEntity | null | undefined;
};

export const ServiceEntity$zodSchema: z.ZodType<ServiceEntity> = z.object({
  active_incidents: z.array(z.string()).nullable().optional(),
  alert_on_add: z.boolean().nullable().optional(),
  allowed_params: z.array(z.string()).nullable().optional(),
  auto_add_responding_team: z.boolean().nullable().optional(),
  checklists: z.array(ChecklistTemplateEntity$zodSchema).nullable().optional(),
  completed_checks: z.int().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  environments: z.array(EnvironmentEntryEntity$zodSchema).nullable().optional(),
  external_resources: z.array(ExternalResourceEntity$zodSchema).nullable()
    .optional(),
  functionalities: z.array(FunctionalityEntity$zodSchema).nullable().optional(),
  id: z.string().nullable().optional(),
  labels: z.record(z.string(), z.any()).nullable().optional(),
  last_import: NullableImportsImportableResourceEntity$zodSchema.nullable()
    .optional(),
  links: z.array(LinksEntity$zodSchema).nullable().optional(),
  managed_by: z.string().nullable().optional(),
  managed_by_settings: z.lazy(() => ManagedBySettings$zodSchema).nullable()
    .optional(),
  name: z.string().nullable().optional(),
  owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
  service_checklist_updated_at: z.iso.datetime({ offset: true }).nullable()
    .optional(),
  service_tier: z.int().nullable().optional(),
  slug: z.string().nullable().optional(),
  teams: z.array(TeamEntityLite$zodSchema).nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  updated_by: NullableAuthorEntity$zodSchema.nullable().optional(),
}).describe("ServiceEntity model");
