/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 13a853b8616c
 */

import * as z from "zod";

export type SignalsAPIOnCallRestrictionEntity = {
  start_day?: string | null | undefined;
  start_time?: string | null | undefined;
  end_day?: string | null | undefined;
  end_time?: string | null | undefined;
};

export const SignalsAPIOnCallRestrictionEntity$zodSchema: z.ZodType<
  SignalsAPIOnCallRestrictionEntity
> = z.object({
  end_day: z.string().nullable().optional(),
  end_time: z.string().nullable().optional(),
  start_day: z.string().nullable().optional(),
  start_time: z.string().nullable().optional(),
});
