/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableSuccinctEntity,
  NullableSuccinctEntity$zodSchema,
} from "./nullablesuccinctentity.js";

/**
 * Signals_API_OnCallShiftEntity model
 */
export type SignalsAPIOnCallShiftEntity = {
  id?: string | null | undefined;
  user?: NullableSuccinctEntity | null | undefined;
  coverage_request?: string | null | undefined;
  color?: string | null | undefined;
  time_zone?: string | null | undefined;
  on_call_schedule?: NullableSuccinctEntity | null | undefined;
  on_call_rotation?: NullableSuccinctEntity | null | undefined;
  team?: NullableSuccinctEntity | null | undefined;
  start_time?: string | null | undefined;
  end_time?: string | null | undefined;
};

export const SignalsAPIOnCallShiftEntity$zodSchema: z.ZodType<
  SignalsAPIOnCallShiftEntity
> = z.object({
  color: z.string().nullable().optional(),
  coverage_request: z.string().nullable().optional(),
  end_time: z.iso.datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  on_call_rotation: NullableSuccinctEntity$zodSchema.nullable().optional(),
  on_call_schedule: NullableSuccinctEntity$zodSchema.nullable().optional(),
  start_time: z.iso.datetime({ offset: true }).nullable().optional(),
  team: NullableSuccinctEntity$zodSchema.nullable().optional(),
  time_zone: z.string().nullable().optional(),
  user: NullableSuccinctEntity$zodSchema.nullable().optional(),
}).describe("Signals_API_OnCallShiftEntity model");
