/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 68c7b7cf64d9
 */

import * as z from "zod";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";
import {
  SignalsAPIOnCallScheduleEntity,
  SignalsAPIOnCallScheduleEntity$zodSchema,
} from "./signalsapioncallscheduleentity.js";

/**
 * Signals_API_OnCallScheduleEntityPaginated model
 */
export type SignalsAPIOnCallScheduleEntityPaginated = {
  data?: Array<SignalsAPIOnCallScheduleEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const SignalsAPIOnCallScheduleEntityPaginated$zodSchema: z.ZodType<
  SignalsAPIOnCallScheduleEntityPaginated
> = z.object({
  data: z.array(SignalsAPIOnCallScheduleEntity$zodSchema).nullable().optional(),
  pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
}).describe("Signals_API_OnCallScheduleEntityPaginated model");
