/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e23eb4fd266e
 */

import * as z from "zod";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";
import {
  NullableSignalsAPIOnCallStrategyEntity,
  NullableSignalsAPIOnCallStrategyEntity$zodSchema,
} from "./nullablesignalsapioncallstrategyentity.js";
import {
  NullableSuccinctEntity,
  NullableSuccinctEntity$zodSchema,
} from "./nullablesuccinctentity.js";
import {
  SignalsAPIOnCallRestrictionEntity,
  SignalsAPIOnCallRestrictionEntity$zodSchema,
} from "./signalsapioncallrestrictionentity.js";
import {
  SignalsAPIOnCallShiftEntity,
  SignalsAPIOnCallShiftEntity$zodSchema,
} from "./signalsapioncallshiftentity.js";
import { SuccinctEntity, SuccinctEntity$zodSchema } from "./succinctentity.js";

/**
 * Signals_API_OnCallRotationEntity model
 */
export type SignalsAPIOnCallRotationEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  time_zone?: string | null | undefined;
  color?: string | null | undefined;
  slack_user_group_id?: string | null | undefined;
  enable_slack_channel_notifications?: boolean | null | undefined;
  prevent_shift_deletion?: boolean | null | undefined;
  coverage_gap_notification_interval?: string | null | undefined;
  members?: Array<SuccinctEntity> | null | undefined;
  shifts?: Array<SignalsAPIOnCallShiftEntity> | null | undefined;
  team?: NullableSuccinctEntity | null | undefined;
  strategy?: NullableSignalsAPIOnCallStrategyEntity | null | undefined;
  restrictions?: Array<SignalsAPIOnCallRestrictionEntity> | null | undefined;
  created_by?: NullableAuthorEntity | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
};

export const SignalsAPIOnCallRotationEntity$zodSchema: z.ZodType<
  SignalsAPIOnCallRotationEntity
> = z.object({
  color: z.string().nullable().optional(),
  coverage_gap_notification_interval: z.string().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  created_by: NullableAuthorEntity$zodSchema.nullable().optional(),
  description: z.string().nullable().optional(),
  enable_slack_channel_notifications: z.boolean().nullable().optional(),
  id: z.string().nullable().optional(),
  members: z.array(SuccinctEntity$zodSchema).nullable().optional(),
  name: z.string().nullable().optional(),
  prevent_shift_deletion: z.boolean().nullable().optional(),
  restrictions: z.array(SignalsAPIOnCallRestrictionEntity$zodSchema).nullable()
    .optional(),
  shifts: z.array(SignalsAPIOnCallShiftEntity$zodSchema).nullable().optional(),
  slack_user_group_id: z.string().nullable().optional(),
  strategy: NullableSignalsAPIOnCallStrategyEntity$zodSchema.nullable()
    .optional(),
  team: NullableSuccinctEntity$zodSchema.nullable().optional(),
  time_zone: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("Signals_API_OnCallRotationEntity model");
