/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 849b8ba8f162
 */

import * as z from "zod";
import {
  NullablePublicApiv1IncidentsSuccinctEntity,
  NullablePublicApiv1IncidentsSuccinctEntity$zodSchema,
} from "./nullablepublicapiv1incidentssuccinctentity.js";
import {
  NullableRulesRuleEntity,
  NullableRulesRuleEntity$zodSchema,
} from "./nullablerulesruleentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";

export type SlimRunbookEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  type?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  attachment_rule?: NullableRulesRuleEntity | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  categories?: Array<string> | null | undefined;
  last_executed_at?: string | null | undefined;
  last_executed_for_incident?:
    | NullablePublicApiv1IncidentsSuccinctEntity
    | null
    | undefined;
};

export const SlimRunbookEntity$zodSchema: z.ZodType<SlimRunbookEntity> = z
  .object({
    attachment_rule: NullableRulesRuleEntity$zodSchema.nullable().optional(),
    categories: z.array(z.string()).nullable().optional(),
    created_at: z.iso.datetime({ offset: true }).nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string().nullable().optional(),
    last_executed_at: z.iso.datetime({ offset: true }).nullable().optional(),
    last_executed_for_incident:
      NullablePublicApiv1IncidentsSuccinctEntity$zodSchema.nullable()
        .optional(),
    name: z.string().nullable().optional(),
    owner: NullableTeamEntityLite$zodSchema.nullable().optional(),
    summary: z.string().nullable().optional(),
    type: z.string().nullable().optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  });
