/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc0368aa061b
 */

import * as z from "zod";

export type SuccinctEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
};

export const SuccinctEntity$zodSchema: z.ZodType<SuccinctEntity> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
});
