/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96e388ef8ca4
 */

import * as z from "zod";
import {
  ChecklistTemplateEntity,
  ChecklistTemplateEntity$zodSchema,
} from "./checklisttemplateentity.js";
import {
  FunctionalityEntityLite,
  FunctionalityEntityLite$zodSchema,
} from "./functionalityentitylite.js";
import {
  MembershipEntity,
  MembershipEntity$zodSchema,
} from "./membershipentity.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";
import {
  NullableIntegrationsMicrosoftTeamsV2ChannelEntity,
  NullableIntegrationsMicrosoftTeamsV2ChannelEntity$zodSchema,
} from "./nullableintegrationsmicrosoftteamsv2channelentity.js";
import {
  NullableIntegrationsSlackSlackChannelEntity,
  NullableIntegrationsSlackSlackChannelEntity$zodSchema,
} from "./nullableintegrationsslackslackchannelentity.js";
import {
  NullableSuccinctEntity,
  NullableSuccinctEntity$zodSchema,
} from "./nullablesuccinctentity.js";
import {
  ServiceEntityLite,
  ServiceEntityLite$zodSchema,
} from "./serviceentitylite.js";
import {
  SlimRunbookEntity,
  SlimRunbookEntity$zodSchema,
} from "./slimrunbookentity.js";

/**
 * TeamEntity model
 */
export type TeamEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  signals_ical_url?: string | null | undefined;
  created_by?: NullableAuthorEntity | null | undefined;
  in_support_hours?: boolean | null | undefined;
  restrict_signals_resource_management?: boolean | null | undefined;
  slack_channel?:
    | NullableIntegrationsSlackSlackChannelEntity
    | null
    | undefined;
  ms_teams_channel?:
    | NullableIntegrationsMicrosoftTeamsV2ChannelEntity
    | null
    | undefined;
  memberships?: Array<MembershipEntity> | null | undefined;
  owned_checklist_templates?: Array<ChecklistTemplateEntity> | null | undefined;
  owned_functionalities?: Array<FunctionalityEntityLite> | null | undefined;
  owned_services?: Array<ServiceEntityLite> | null | undefined;
  owned_runbooks?: Array<SlimRunbookEntity> | null | undefined;
  responding_services?: Array<ServiceEntityLite> | null | undefined;
  services?: Array<ServiceEntityLite> | null | undefined;
  functionalities?: Array<FunctionalityEntityLite> | null | undefined;
  default_signals_escalation_policy?: NullableSuccinctEntity | null | undefined;
};

export const TeamEntity$zodSchema: z.ZodType<TeamEntity> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  created_by: NullableAuthorEntity$zodSchema.nullable().optional(),
  default_signals_escalation_policy: NullableSuccinctEntity$zodSchema.nullable()
    .optional(),
  description: z.string().nullable().optional(),
  functionalities: z.array(FunctionalityEntityLite$zodSchema).nullable()
    .optional(),
  id: z.string().nullable().optional(),
  in_support_hours: z.boolean().nullable().optional(),
  memberships: z.array(MembershipEntity$zodSchema).nullable().optional(),
  ms_teams_channel: NullableIntegrationsMicrosoftTeamsV2ChannelEntity$zodSchema
    .nullable().optional(),
  name: z.string().nullable().optional(),
  owned_checklist_templates: z.array(ChecklistTemplateEntity$zodSchema)
    .nullable().optional(),
  owned_functionalities: z.array(FunctionalityEntityLite$zodSchema).nullable()
    .optional(),
  owned_runbooks: z.array(SlimRunbookEntity$zodSchema).nullable().optional(),
  owned_services: z.array(ServiceEntityLite$zodSchema).nullable().optional(),
  responding_services: z.array(ServiceEntityLite$zodSchema).nullable()
    .optional(),
  restrict_signals_resource_management: z.boolean().nullable().optional(),
  services: z.array(ServiceEntityLite$zodSchema).nullable().optional(),
  signals_ical_url: z.string().nullable().optional(),
  slack_channel: NullableIntegrationsSlackSlackChannelEntity$zodSchema
    .nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
}).describe("TeamEntity model");
