/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";
import { TeamEntity, TeamEntity$zodSchema } from "./teamentity.js";

/**
 * TeamEntityPaginated model
 */
export type TeamEntityPaginated = {
  data?: Array<TeamEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const TeamEntityPaginated$zodSchema: z.ZodType<TeamEntityPaginated> = z
  .object({
    data: z.array(TeamEntity$zodSchema).nullable().optional(),
    pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
  }).describe("TeamEntityPaginated model");
