/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a02afefc530b
 */

import * as z from "zod";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";

export type TeamEntityLite = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  signals_ical_url?: string | null | undefined;
  created_by?: NullableAuthorEntity | null | undefined;
  in_support_hours?: boolean | null | undefined;
  restrict_signals_resource_management?: boolean | null | undefined;
};

export const TeamEntityLite$zodSchema: z.ZodType<TeamEntityLite> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  created_by: NullableAuthorEntity$zodSchema.nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  in_support_hours: z.boolean().nullable().optional(),
  name: z.string().nullable().optional(),
  restrict_signals_resource_management: z.boolean().nullable().optional(),
  signals_ical_url: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
});
