/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5bbcbbf73a3f
 */

import * as z from "zod";
import {
  IncidentsRetrospectiveFieldEntity,
  IncidentsRetrospectiveFieldEntity$zodSchema,
} from "./incidentsretrospectivefieldentity.js";
import {
  UpdateIncidentRetrospectiveField,
  UpdateIncidentRetrospectiveField$zodSchema,
} from "./updateincidentretrospectivefield.js";

export type UpdateIncidentRetrospectiveFieldRequest = {
  retrospective_id: string;
  field_id: string;
  incident_id: string;
  update_incident_retrospective_field: UpdateIncidentRetrospectiveField;
};

export const UpdateIncidentRetrospectiveFieldRequest$zodSchema: z.ZodType<
  UpdateIncidentRetrospectiveFieldRequest
> = z.object({
  field_id: z.string(),
  incident_id: z.string(),
  retrospective_id: z.string(),
  update_incident_retrospective_field:
    UpdateIncidentRetrospectiveField$zodSchema,
});

export type UpdateIncidentRetrospectiveFieldResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Incidents_RetrospectiveFieldEntity?:
    | IncidentsRetrospectiveFieldEntity
    | undefined;
};

export const UpdateIncidentRetrospectiveFieldResponse$zodSchema: z.ZodType<
  UpdateIncidentRetrospectiveFieldResponse
> = z.object({
  ContentType: z.string(),
  Incidents_RetrospectiveFieldEntity:
    IncidentsRetrospectiveFieldEntity$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
