/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4c090827387
 */

import * as z from "zod";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";
import { UserEntity, UserEntity$zodSchema } from "./userentity.js";

/**
 * UserEntityPaginated model
 */
export type UserEntityPaginated = {
  data?: Array<UserEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const UserEntityPaginated$zodSchema: z.ZodType<UserEntityPaginated> = z
  .object({
    data: z.array(UserEntity$zodSchema).nullable().optional(),
    pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
  }).describe("UserEntityPaginated model");
